include:
  - res/docker-compose/hub+chrome+firefox.yaml

services:
  httpd:
    image: in2code/httpd:2.4-alpine
    #healthcheck:
    #  test: wget --no-check-certificate --no-verbose --tries=1 --spider https://web.local.co-stack-test.com || exit 1
    #  interval: 15s
    #  retries: 5
    #  start_period: 10s
    #  timeout: 10s
    volumes:
      - ./:/app/
    environment:
      VIRTUAL_HOST: web.local.co-stack-test.com
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: https
    networks:
      default:
        aliases:
          - web.local.co-stack-test.com

  php:
    image: in2code/php-dev:8.1-fpm
    volumes:
      - ./:/app/
      - $HOME/.composer/auth.json:/tmp/composer/auth.json
      - $HOME/.composer/cache/:/tmp/composer/cache/
      - $HOME/.phive/:/tmp/phive/
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK

  mysql:
    image: in2code/mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - 15622:3306

  mail:
    image: axllent/mailpit
    environment:
      VIRTUAL_HOST: mail.local.co-stack-test.com
      VIRTUAL_PORT: 8025

volumes:
  mysql-data:
