version: '3.8'

services:
  selenium-hub:
    image: selenium/hub
    shm_size: 2gb
    healthcheck:
      test: '/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444'
      interval: 15s
      timeout: 30s
      retries: 5
    environment:
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_OVERRIDE_MAX_SESSIONS: true
      SE_NODE_MAX_SESSIONS: 5

  selenium-node-chrome:
    image: selenium/node-chrome
    shm_size: 2gb
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_OVERRIDE_MAX_SESSIONS: true
      SE_NODE_MAX_SESSIONS: 5
      SE_VNC_NO_PASSWORD: 1
    ports:
      - ${SELENIUM_NODE_CHROME_VNC_PORT:-14320}:5900

  selenium-node-firefox:
    image: selenium/node-firefox
    shm_size: 2gb
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_OVERRIDE_MAX_SESSIONS: true
      SE_NODE_MAX_SESSIONS: 5
      SE_VNC_NO_PASSWORD: 1
    ports:
      - ${SELENIUM_NODE_FIREFOX_VNC_PORT:-14321}:5900
